spring:
  datasource:
    url: jdbc:h2:mem:happy-town;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: true
        format_sql: true
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false

mail:
  smtp:
    host: 172.24.0.3
    port: 25
    from: mairie@happytown.com

file:
  cadeauxByTrancheAge:
    path: src/main/resources/cadeaux.txt

happytown:
  openapi:
    url: "http://localhost:8080"
    server:
      url: "http://localhost:8080"
      description: "Happy Town Clone API"
    contact:
      email: "theophile.banogo@gmail.com"
      name: "Serge BANOGO"
      url: "https://happytownclone.com/"
    licence:
      url: "MIT"
    info:
      title: "Happy Town Clone"
      version: "1.0"
      description: "This API exposes endpoints to manage tutorials"
      termsOfService: "https:://happytownclone.com/terms"

